In [48]:
elements=str(input())
if len(elements)!=9:
    raise SystemExit("Error! Excepted 9 characters - entred", len(elements))
import numpy as np
a = np.arange(9).reshape((3,3))
for i in range (3):
    for j in range (3):
        a[i][j]=elements[i*2+j+i]
print (elements, a, int(linalg.det(a)), sep='\n')

 098765432


098765432
[[0 9 8]
 [7 6 5]
 [4 3 2]]
30
